name: tdmpc
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9
  - torchvision
  - cudatoolkit
  - pip
  - pip:
    - termcolor
    - omegaconf
    - gym
    - dm-control
    - pandas
    - wandb
    - moviepy
    - imageio
    - gym
